#!/bin/sh

xrdb ~/.Xresources
#nitrogen --restore &
# xset +fp /usr/share/fonts/local &
xset fp rehash &
xsetroot -cursor_name left_ptr &
#xmodmap ~/.speedswap

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
# if [ -x $HOME/bin/external_monitor.sh ];then
#   sh $HOME/bin/external_monitor.sh &
# fi

bspc config border_width        2
bspc config window_gap          9
bspc config bottom_padding 0
bspc config top_padding 0 
bspc config focused_border_color '#'$C6
bspc config normal_border_color '#'$C0
bspc config presel_feedback_color '#'$C4
bspc config honor_size_hints true
bspc config split_ratio         0.52
bspc config borderless_monocle  false 
bspc config gapless_monocle     false 
bspc config focus_follows_pointer true

external_monitor=$(xrandr --query | grep 'HDMI2')
if [[ $external_monitor = *connected* ]]; then
    xrandr --output HDMI2 --mode 3840x2160 --primary --output eDP1 --mode 1366x768 --right-of HDMI2 &
    bspc monitor HDMI2 -d 1 2 3 4 5 6 
    bspc monitor eDP1 -d 7 8 9 10 11 12
else
    bspc monitor eDP1 -d 1 2 3 4 5 6
fi

bspc rule -a 'Firefox' desktop=^2
bspc rule -a 'Zathura' state=tiled desktop=^3
bspc desktop ^3 -l monocle

sh ~/.fehbg &
#urxvtd -q -o -f &
sh ~/bin/bspwmfloatingdesktop.sh &
#sxhkd &
# dropbox-cli start &
#sh ~/.config/bspwm/panel/info | dzen2 -p -y -1 -fn inconsolata:size=11 &
#compton --config ~/.config/compton.conf &
#compton -b --xrender-sync --xrender-sync-fence &
picom -b
(sleep 1s && unclutter -idle 1 -jitter 2 -root) &
#(sleep 1s && pnmixer) &
#(sleep 3s && conky -d -c /home/oli/.conkyrc) &
#(sleep 4s && xfce4-power-manager) &
#(sleep 6s && sh /home/oli/bin/conky-stat.sh) &
# (sleep 2s && sh /home/oli/bin/update-startpage.sh) &
(sleep 2s && sh /home/oli/bin/update-zathura.sh) &
#(sleep 2s && sh /home/oli/bin/update-pentadactcyle.sh) &
